### ISSUE TITLE
Replying to a private message sends the reply to myself instead of the person I'm replying to.

### ISSUE THREAD

**Issue by DazzaJay** [dessalines/jerboa#959] opened 2023-07-03 04:29 UTC
**Jerboa Version**
0.0.37

**Android version + phone**
Nothing Phone (1), Nothing OS 1.5.4 (Android 13)

**Describe the bug**
After receiving a private message, pressing reply and replying won't send the reply to the intended person, instead it sends it to myself.

**To Reproduce**

1. Receive a direct message.
2. Press the reply button at the bottom right.
3. Type your reply and press send.
4. Be amazed that it instead sent it to yourself.

Example screenshot, Aussie Bob replied to the user pornonmain, however the reply was sent to Aussie Bob instead of pornonmain.
![Screenshot_20230703-141539~2](https://github.com/dessalines/jerboa/assets/3713158/3332f6fb-3882-4246-9174-06f15bfbc9b2)

**Comment by sockenklaus** [comment] 2023-07-03 11:15
This is a dupe of #837

**Comment by DazzaJay** [comment] 2023-07-03 11:33
> This is a dupe of #837

I apologize for the duplicate. i did search first, but obviously not well enough.

**Closed** 2023-07-03 14:28 UTC
Labels: bug
