### ISSUE TITLE
Explain symbol when post was removed

### ISSUE THREAD

**Issue by firefoxlover** [dessalines/jerboa#1458] opened 2024-03-19 18:41 UTC
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

![Screenshot_20240319-193654](https://github.com/dessalines/jerboa/assets/78762110/3d73442e-3e30-414a-a3da-84453b6076c9)

My post seems to have been removed.

Kinda related to another bug, asking for infos "why did this happen". Not sure if this is a general Lemmy issue, doesnt there need to be a notification when such an action is done?

I had comments under the post and couldnt reply, `post deleted` but it was not clear if the comment or post. And to this time I got no notification and dont even know what happened.

The symbol in the post is not explained, a popup when pressing it may be useful.

Latest Github Jerboah release

**Comment by MV-GH** [comment] 2024-03-20 18:40
@dessalines does Lemmy do anything to notify the affected user of any moderation action?

If it doesn't you will have to request this feature on Lemmy.

At most Jerboa can detect instance bans. But it can't check all your posts and comments.

**Comment by MV-GH** [comment] 2024-03-20 21:51
Also see #1319

I am very hesitant to make those icons touchable. It just means more touch areas that would be accidentally hit when you want to do something unrelated.

At minimum we are adding a explanation in the readme, and possible the a help page in Jerboa that explains all the icons

**Comment by firefoxlover** [comment] 2024-03-24 13:04
I think touching the icons is not a problem as it doesnt occur often. Documenting them somewhere in the app would be best

**Comment by dessalines** [comment] 2024-03-25 21:10
The back-end doesn't notify you of mod actions currently. 

This is also a dupe of #1319

**Closed by dessalines** 2024-03-25 21:10 UTC
Labels: enhancement
