### ISSUE TITLE
Inbox reply interactions missing

### ISSUE THREAD

**Issue by Stugist** [dessalines/jerboa#525] opened 2023-06-11 09:01 UTC
** Jerboa Version **
0.0.33

**Describe the bug**
Buttons are missing below inbox rrplies

**To Reproduce**

1. Go to inbox
2. See error
![Screenshot_20230611_095403_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/102943350/5992c8e4-cab2-4f3f-8211-259712a61816)

**Comment by Stugist** [comment] 2023-06-11 09:12
Made a post in c/Jerboa, other folk are reporting the same.

**Comment by Stugist** [comment] 2023-06-11 09:14
Other folk are confirming on my post in c/Jerboa.
Accidentally clicked the wrong button with my damned sausage fingers, issue is not closed.

**Comment by Stugist** [comment] 2023-06-11 10:12
Not a bug, a feature. Inbox interaction collapse needs to be added to 0.0.33 update documentation as it's not currently mentioned.

**Comment by 0hCome0n** [comment] 2023-06-12 00:42
The toggle for "show action bar by default fit comments" doesn't work for replies in your inbox. They're already collapsed by default regardless of the toggle. That's the real bug.

**Comment by Riftr** [comment] 2023-06-12 04:18
> The toggle for "show action bar by default fit comments" doesn't work for replies in your inbox. They're already collapsed by default regardless of the toggle. That's the real bug.

It's a bit more than this as you can't show the controls at all currently. The only option you have is to press on the header of the inbox message that takes you to the top of the post that reply is buried in.

**Comment by Stugist** [comment] 2023-06-12 04:20
This is not true, currently if you long press in the space beside the username it expands the action bar.

**Comment by Riftr** [comment] 2023-06-12 04:26
> This is not true, currently if you long press in the space beside the username it expands the action bar.

Ah ha! You are correct but I could not figure this out and I thought I'd pressed everywhere that made sense at least.

**Comment by Stugist** [comment] 2023-06-12 05:18
> Ah ha! You are correct but I could not figure this out and I thought I'd pressed everywhere that made sense at least.

It took a bunch of us over in c/Jerboa the better part of an hour to figure it out, don't feel bad.

**Comment by beatgammit** [comment] 2023-06-14 04:17
> currently if you long press in the space beside the username it expands the action bar.

For me it collapses the entire post, not just the action bar, which doesn't seem to cause this.

Can you give the step-by-step process to reproduce this? I'm willing to look into fixing this, but I'm not sure how to reproduce. I think for now disabling the click next to the username while in the inbox makes the most sense, but I'm not sure if someone actually wants that feature. I use it a ton for collapsing comment threads, but not for inbox replies.

**Comment by 0hCome0n** [comment] 2023-06-14 04:54
![Screenshot_20230614-003303~2](https://github.com/dessalines/jerboa/assets/135261443/6f6c3140-9c6f-4f85-b316-16af9fb843be)

For me the action bar is closed by default in the inbox regardless of how the toggle in the settings is set.

Key for the image:

Top White: Post Title
Blue: Username
Green: Community
Bottom White: Comment
Brown/Gold Highlight: Active Area

For me, long pressing on the active area will expand and collapse the action bar.

Tapping on the active area will collapse and expand the comment.

If you collapse the comment while the action bar is expanded, the action bar is hidden with the comment but its expanded/collapsed state doesn't change. You can expand and collapse the action bar while the whole comment is collapsed, though you have to expand the comment to verify the state of the action bar.

Note that this active area includes the comment time indicator but not the username.

**Comment by Stugist** [comment] 2023-06-14 05:08
It took me about 6 tries after knowing how it was done to be able to get it to work. Basically press and hold. Bit tricky to do when you have sausage fingers.

**Comment by beatgammit** [comment] 2023-06-14 08:56
Ok, apparently my phone was stuck on an older version (0.0.32) for some reason. I can now reproduce it, so I'll work on a fix.

**Comment by beatgammit** [comment] 2023-06-14 09:18
I tracked it down, looks like a really easy fix. My change merely fixes the default behavior here, you can still disable the action bar in the settings. Whether that's desired is a separate issue.

**Closed** 2023-06-14 13:20 UTC
Labels: bug, 5 - high priority
