### ISSUE TITLE
Make the back button take you to the home tab first

### ISSUE THREAD

**Issue by DefinitelyNotFred** [dessalines/jerboa#1128] opened 2023-08-03 03:44 UTC
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Currently, if you press the back button when in the search, inbox, etc, tabs it will notify you that you can press it again to close the app. I find this very unintuitive though, what I would expect to happen is for the back button to take me to my home tab first before attempting to close.

**Comment by MV-GH** [comment] 2023-08-03 04:02
Currently the design choice, is that the navigation buttons reset the navigation history. Duplicate of #1008

**Closed** 2024-02-10 23:30 UTC
Labels: enhancement
