### ISSUE TITLE
Jerboa crashing immediately after update to 0.0.37

### ISSUE THREAD

**Issue by konstantinpae** [dessalines/jerboa#911] opened 2023-06-29 12:01 UTC
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13 (June 5th) on Pixel 6 Pro

**Describe the bug**
Jerboa crashes when opened. This only happened after the update from Play Store. Very briefly the "What's new" bubble is visible then the app completely crashes. 

**To Reproduce**
Open Jerboa

**In the case of a crash**

```
<details><summary>LOGS</summary>
--------- beginning of crash
06-29 13:57:28.269 13669 13669 E AndroidRuntime: FATAL EXCEPTION: main
06-29 13:57:28.269 13669 13669 E AndroidRuntime: Process: com.jerboa, PID: 13669
06-29 13:57:28.269 13669 13669 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend, parameter sortType
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at com.jerboa.ui.components.home.SiteViewModel$getSite$1.invokeSuspend(Unknown Source:111)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
06-29 13:57:28.269 13669 13669 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3da2935, Dispatchers.Main.immediate]
</details>
```

**Comment by Gil231b** [comment] 2023-06-29 14:20
I had the same issue and I managed to solve it clearing the cache of the app.

**Comment by seamuslowry** [comment] 2023-06-29 15:02
> I had the same issue and I managed to solve it clearing the cache of the app.

Clearing the cache for the app did not resolve it for me

**Comment by konstantinpae** [comment] 2023-06-29 15:04
> I had the same issue and I managed to solve it clearing the cache of the app.
Also tried cleaning the cache to no avail. Did not try a reinstall yet, in case more logs of the crash are needed.

**Comment by DraconicNEO** [comment] 2023-06-29 15:20
I wasn't able to get it work either, i tried clearing data and reinstalling but even though it fixed the issue it still came back anyway after a bit.

However I did find a workaround, if I patch the app in app cloner to ignore crashes and to disallow self-killing the app works just fine and doesn't crash. I'm assuming that whatever caused the crash isn't anything severe enough to stop the app working in its tracks.

Important Note: I would not recommend this as a permanent fix and I'm sure the Devs wouldn't either (probably wouldn't recommend you do it at all), I just did it for Testing purposes and because I need Jerboa as a fallback client in case Liftoff isn't working.

**Comment by MV-GH** [comment] 2023-06-29 18:45
Oh i think i know what might be the cause. Our sortTypes have not included yet the new ones such as Last6Hours last12Hours. The logs would confirm this

**Comment by Vitalya-code** [comment] 2023-06-29 18:49
Same issue

**Comment by MV-GH** [comment] 2023-06-29 18:52
> Same issue

Can you check on the lemmy site itself and see what your default sort type is set to.

**Comment by MV-GH** [comment] 2023-06-29 19:21
Nvm confirmed it myself ill have a fix out soon

**Comment by Vitalya-code** [comment] 2023-06-29 20:28
> > Same issue
> 
> Can you check on the lemmy site itself and see what your default sort type is set to. 

My default sort type is set to "hot" and type to "subscribed"

**Comment by MV-GH** [comment] 2023-06-29 20:41
Hmm weird, i am gonna need your logs then, but the OP issue will be fixed soon

**Comment by Rustmilian** [comment] 2023-06-29 21:21
@MV-GH 
> Hmm weird, i am gonna need your logs then, but the OP issue will be fixed soon

I have an idea as to why this is happening.
Many users are using a Lemmy.world account which is having trouble upgrading to v0.18, so if the user had previously logged into the account prior to updating the app would try loading the account/instance and then crash. Ofc this is an educated guess but it ties into another issue that I'll be opening in a moment.

**Comment by MV-GH** [comment] 2023-06-29 21:21
For all the ppl experiencing this bug, your options are:
- Reset your default sorting type in the browser to one that existed before 0.17.
- Delete your app data, so that you will start as anonymous (dont log in with the acount that has that sorting type)
- Install this apk which has the fix included [app-release.zip](https://github.com/dessalines/jerboa/files/11910589/app-release.zip)
- Wait until 0.38 gets release

**Comment by jpotier** [comment] 2023-07-02 15:33
Can confirm that the provided https://github.com/dessalines/jerboa/files/11910589/app-release.zip fixes this issue.

**Comment by MV-GH** [comment] 2023-07-25 22:02
Closing as no longer relevant

**Closed by MV-GH** 2023-07-25 22:02 UTC
Labels: bug
