### ISSUE TITLE
Bottom panel has duplicated "search". 

### ISSUE THREAD

**Issue by jy-r** [dessalines/jerboa#787] opened 2023-06-21 06:06 UTC
** Jerboa Version **
0.0.34

** Describe the bug **
For me, bottom panel has "Home", "Search" (which controls communities), "Inbox", "Search" (which seems to be related to saved posts) and "Profile". I think both of the "Search" buttons should be renamed to "Communities" and "Saved" retrospectively.

**Comment by sockenklaus** [comment] 2023-06-21 08:17
This is a duplicate of #604, #653, #675, #741, #757 and has been fixed in #608.

**Closed** 2023-06-21 08:19 UTC
Labels: bug
