### ISSUE TITLE
Swipe from left to go back inside thread

### ISSUE THREAD

**Issue by csm10495** [dessalines/jerboa#481] opened 2023-06-09 15:23 UTC
- [ x] Did you check to see if this issue already exists?
- [x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

When inside a thread, swipe from left to go back to previous page.

**Comment by dessalines** [comment] 2023-06-09 20:29
Dupe of #431

**Closed by dessalines** 2023-06-09 20:29 UTC
Labels: enhancement
