### ISSUE TITLE
[FR] Allow to search across the known Lemmy Fediverse

### ISSUE THREAD

**Issue by momobobe** [dessalines/jerboa#177] opened 2022-06-25 07:27 UTC
This might be a long-run feature, so take your time. Consider to integrate known instances and allow users to choose in which instances (or all) to search. This could be helpful for new users to get familiar with Fediverse.

**Comment by dessalines** [comment] 2022-06-27 01:31
Dupe of #27

**Closed by dessalines** 2022-06-27 01:31 UTC
