### ISSUE TITLE
Add ability to search existing posts in a community

### ISSUE THREAD

**Issue by neurozero** [dessalines/jerboa#467] opened 2023-06-08 21:49 UTC
- [ x ] Did you check to see if this issue already exists?
- [ x ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ x ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

When adding a new post to a Lemmy community, currently the best option to make sure it isn't a repost from inside the app (say if you're providing a news link) is to read through the existing posts manually to find similar posts. On active communities this can be difficult, and as communities get busier it will be even more difficult.

Having a search function inside the app would make this much easier. Also a search function would be useful in general, just for finding posts you read previously or when you're looking for a specific topic.

**Comment by dessalines** [comment] 2023-06-09 20:23
Here's the issue for search: #27 , I've updated it 

It needs to be very similar to lemmy-ui, where it can filter by type of content returned, creator, community, etc. 

Closing as dupe of #27

**Closed by dessalines** 2023-06-09 20:23 UTC
Labels: enhancement
