### ISSUE TITLE
warning when opening links

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1036] opened 2023-07-14 12:37 UTC
youre about to be redirected to:
garfieldcomics.com.
are you sure

**Comment by RustoMCSpit** [comment] 2023-07-17 00:16
also should warn if it doesnt supoort https or if ublock finds it suspicious

**Comment by twizmwazin** [comment] 2023-07-19 20:09
Duplicate of #434

**Closed by twizmwazin** 2023-07-19 20:09 UTC
Labels: enhancement
