### ISSUE TITLE
Parent comment navigation buttons block bottom of comments

### ISSUE THREAD

**Issue by anonderpling** [dessalines/jerboa#883] opened 2023-06-25 23:23 UTC
On acting to the bottom of a page on my tablet, I can't use the toolbox for the last comment (to vote or reply), as it's covered by the up/down vote icons for the main post. [Screenshot](https://github.com/dessalines/jerboa/assets/125647602/14b43871-9641-49ab-aac2-f230d578ef63)

**Comment by twizmwazin** [comment] 2023-06-26 01:02
I've edited your issue down to just point 1, in the future please make separate issues for each item. Regarding 2, that will be fixed when #817 is merged. For 3, draft support is being worked on in #844 which should mitigate that. I don't think the bottom nav would work well in the comments and community views because they don't really correspond to any of the bottom nav elements.

**Comment by yate** [comment] 2023-07-08 02:59
@anonderpling What's your tablet model and Android version? I wasn't able to reproduce this in an emulator

**Comment by dessalines** [comment] 2024-02-10 22:44
Stale, can't repro.

**Closed by dessalines** 2024-02-10 22:44 UTC
Labels: bug, 3 - medium priority
