### ISSUE TITLE
Black theme doesn't set the android status bar to black

### ISSUE THREAD

**Issue by obosob** [dessalines/jerboa#661] opened 2023-06-15 02:59 UTC
** Jerboa Version **
0.0.33

**Describe the bug**
When in Black theme the status bar on android, remains the same colour as the background colour in Dark mode, rather than matching the theme.

![Screenshot_20230615-035813.png](https://github.com/dessalines/jerboa/assets/1075229/c542b7c6-74a3-4e49-bb2b-05f6352ac2e0)

![Screenshot_20230615-035803.png](https://github.com/dessalines/jerboa/assets/1075229/3f6f4297-9471-4355-aac2-21d21a0a71b4)

**To Reproduce**

1. Go to 'Settings > Look and feel'
2. Click on 'Theme'
3. Select 'Black'
4. Observe the status bar

**Comment by Schoolkid1** [comment] 2023-06-16 10:26
I'm going to pick this issue up for my school project. Does any one knows if there is a coding standard available? If there is not i will of course do my best to work as neat as possible.

**Comment by Schoolkid1** [comment] 2023-06-16 11:25
On my phone (Oppo A78) the toolbar does match. Could you tell me what device you are using?

![Screenshot_2023-06-16-13-23-11-52_a10f969cf1c4adf2c503042b459b8476](https://github.com/dessalines/jerboa/assets/119050023/56e0b79c-76a8-44b8-96cb-3f46b6517baa)

**Comment by Schoolkid1** [comment] 2023-06-19 02:05
@dessalines I am not getting response and after checking on my android phone I concluded the issue doesn't show up. Shall we close this issue?

**Comment by obosob** [comment] 2023-06-19 13:48
This is on a Google Pixel 6, sorry for late reply.

**Comment by Schoolkid1** [comment] 2023-06-21 12:59
For me this problem is not reproduce-able. In combination with the deadline for my school year I am going to focus on another issue. Maybe some one else wants to pick up this issue?

**Comment by MV-GH** [comment] 2023-07-25 22:10
What android version?

**Comment by Schoolkid1** [comment] 2023-08-09 23:46
It seems the Google Pixel uses a different buildup in the way it shows colors when changing theme, to resolve this issue i added in the Color.kt file an extra value to adjust specifically the toolbar color. I staged the change, can some one check if this value is sufficient to solve this issue?

**Comment by MV-GH** [comment] 2023-08-10 05:05
@Schoolkid1 make a PR with your proposed changes

**Comment by MV-GH** [comment] 2023-08-11 03:08
I do not see the PR. Also the reason your changes are combined, is that you did both changes on the same branch.

Take a look at this article: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

And this one for setting upstream as the above does not seem to mention it
https://devopscube.com/set-git-upstream-respository-branch/

or this but it's pretty lengthy https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

**Comment by Schoolkid1** [comment] 2023-08-11 05:30
I do have a link for the PR , it is https://github.com/MV-GH/jerboa/pull/1

But i will delete my fork and reinstall it and do it following the given steps.

**Comment by MV-GH** [comment] 2023-08-11 05:37
Be carefully, with deleting your fork, it will also delete your changes. Keep the fork make a new one, until you have it setup as above and recreated your changes their in separate branch. I see that PR but that one is a PR to my fork. You need to do a PR to this repository (upstream). As you can see it has also many conflicts, this is because it is quite behind on changes from upstream. If you have it setup as above it will be very easy to pull the changes from upstream and then merge them into your branches with the changes.

**Comment by Schoolkid1** [comment] 2023-08-11 06:01
New link to PR https://github.com/dessalines/jerboa/pull/1167

Is this better?

**Comment by dessalines** [comment] 2024-02-10 22:01
Stale issue, and doesn't seem to be an issue.

**Closed by dessalines** 2024-02-10 22:01 UTC
Labels: bug, 4 - medium/high priority
