### ISSUE TITLE
Backspace behaving oddly (deletes spaces between previous words) 

### ISSUE THREAD

**Issue by Sparrowkeet** [dessalines/jerboa#1340] opened 2024-02-01 18:12 UTC
### Jerboa Version

0.0.55

### Android Version + Phone

Android 13, Google Pixel 4a running GrapheneOS

### Describe The Bug

After typing a few words and then hitting backspace a few times, the space between two previous words is deleted (see video for example). Observed in comments and new posts.

https://github.com/dessalines/jerboa/assets/148015728/cf25cd01-029b-4d0c-a0ec-95aef82f5f97

### To Reproduce

1. Go to any text field in Jerboa (comment or new post)
2. Type a few words
3. Hit backspace several times
4. The space between two previous words disappears

**Comment by dessalines** [comment] 2024-02-05 03:20
Jetpack compose text field issues. Dupe of #194

**Closed by dessalines** 2024-02-05 03:20 UTC
Labels: bug
