### ISSUE TITLE
App crashing on launch with most recent update

### ISSUE THREAD

**Issue by NaitsirkC** [dessalines/jerboa#917] opened 2023-06-29 18:51 UTC
**Jerboa Version**
0.0.37

**Android version + phone**
Android 13 S23+ oneui 5.1

**Describe the bug**
The app crashes when opening. It starts on the main feed (no feed though, just black, but you can still see the top and bottom bars), it loads for a second or two then crashes

**To Reproduce**

Open the app

**Comment by Rustmilian** [comment] 2023-06-29 19:34
Clear the storage of the app completely.

**Comment by Arian04** [comment] 2023-06-29 19:35
Duplicate of #911

**Comment by NaitsirkC** [comment] 2023-06-30 13:57
I did that and now I can't log in at all. I can still log in with no issue
on the website or in other apps.

**Comment by MV-GH** [comment] 2023-07-25 22:02
Closing as no longer relevant

**Closed by MV-GH** 2023-07-25 22:02 UTC
Labels: bug
