### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by s0mt0chukwu** [dessalines/jerboa#977] opened 2023-07-06 02:11 UTC
After putting in my instance which is Lemmy.sdf.org
App unexpectedly shut down 
Tried it a lot of times and it keeps repeating the same behavior

**Comment by MV-GH** [comment] 2023-08-04 12:08
Can you still reproduce this behaviour in the latest version of Jerboa? I can't attempt a reproduction as that instance seems to be down at the time of writing this.

**Comment by s0mt0chukwu** [comment] 2023-08-05 03:07
Jerboa sucks 

I tried other Lemmy clients and it worked

**Comment by MV-GH** [comment] 2023-08-05 03:40
Thanks, for your constructive and mature feedback. Do consider that Jerboa is written entirely by volunteers in their spare time.

I will close this until you drop this unproductive attitude and provide me with the logs. Have a nice day!

**Closed** 2023-08-05 03:41 UTC
Labels: bug
