### ISSUE TITLE
Settings reverted to default when saving settings

### ISSUE THREAD

**Issue by Alatarius** [dessalines/jerboa#862] opened 2023-06-24 02:25 UTC
**Jerboa Version*
0.0.35

**Describe the bug**
I change settings to my liking then press the save settings button at the bottom, bit the moment I leave the settings page all settings revert to default.

**To Reproduce**

1. Go to Settings
2. Alter settings to you preference
3. Press save settings button the exit settings

[edited for spelling error]

**Comment by beatgammit** [comment] 2023-06-24 22:26
I think this is fixed with this PR: #854. So probably in the next release.

Note, that PR only touches the sort and listing type (buttons at the top of the main view), so if there's anything else, please update this issue with those other settings.

We'll need a better long-term fix because the process we currently use is error-prone, so perhaps we should address it as part of the fix for #840. Essentially, ViewModels should use LiveData so manual updates aren't necessary.

**Comment by Alatarius** [comment] 2023-06-25 01:29
Mine happens with every setting not just sort and listing. Show/hide NSFW, nav bar setting, etc. And I do mean every setting gets reverted to default upon saving and exiting the settings menu. Even avatar gets set to default in saving

**Comment by beatgammit** [comment] 2023-06-25 04:09
Try saving, then quitting the app and come back. Does that work? I've seen a few cases where the settings updates just don't get applied. If that doesn't work, then your settings aren't being saved.

**Comment by Alatarius** [comment] 2023-06-25 19:37
That didn't work either. No settings of any kind can be saved. Everything reverts back to default.

**Comment by Alfaa123** [comment] 2023-07-20 22:14
I am also having this problem. Signed in properly to lemmy.world but profile settings do not save. I occasionally get a toast that says something about a connection error.

The "save settings" button greys out and stays grey when I press it only sometimes. Other times it turns grey for a half second and reverts to blue.

**Comment by MV-GH** [comment] 2023-08-10 18:00
Can you still reproduce this in the latest version?

**Comment by MV-GH** [comment] 2023-09-17 15:47
I am closing this for now.

**Closed by MV-GH** 2023-09-17 15:47 UTC
Labels: bug
