### ISSUE TITLE
Jerboa delete space between two words instead of deleting a char of the word

### ISSUE THREAD

**Issue by Domefemia** [dessalines/jerboa#1032] opened 2023-07-13 19:49 UTC
**Jerboa Version**
0.0.39

**Android version + phone**
Android 13 LineageOS-20-microg PocoX3NFC

**Describe the bug**
When deleting a character in a text with 2 or more words, jerboa instead of the deleting the character delete the space between the words. 

For example the text "Ciao questo è un test di jerboa" everything works fine until we get to "Ciao questo è un test d" if I try to delete the d at the end jerboa delete the space between "test" and "d" instead

**To Reproduce**

1. Go to publish a comment or post (in the contemt section)
2. Write something
3. Try deleting the text you have just typed

Video of the bug:
https://github.com/dessalines/jerboa/assets/50798132/2e4f197a-90a9-4616-8130-59115009e737

**Comment by MV-GH** [comment] 2023-07-13 20:13
Duplicate of #194

**Closed by MV-GH** 2023-07-13 20:13 UTC
