### ISSUE TITLE
Look & feel menu is not scrollable

### ISSUE THREAD

**Issue by ReddishPython** [dessalines/jerboa#813] opened 2023-06-22 06:49 UTC
**Jerboa Version**
0.0.33 from google play store

**Describe the bug**
Unable to scroll down in the look&feel section of the settings menu

**To Reproduce**
simply open the aforementioned menu

Here is what I see, i cannot scroll down in both orientations

![IMG_20230622_084538](https://github.com/dessalines/jerboa/assets/67278807/f81fda9c-66d6-4d5c-98a3-3b72ebf4a583)
![IMG_20230622_084524](https://github.com/dessalines/jerboa/assets/67278807/ef5e894d-3ae9-4bb1-9520-bc81f666326c)

**Comment by beatgammit** [comment] 2023-06-22 15:35
This is really annoying, I might take a look at it later today.

**Comment by daviessm** [comment] 2023-06-22 17:23
Duplicate of #660, is fixed in 0.0.34 (not on the Play Store).

**Closed** 2023-06-22 17:54 UTC
Labels: bug
