### ISSUE TITLE
It's hard to read logged in account name when looking at the side menu in light theme

### ISSUE THREAD

**Issue by tarekzoabi19** [dessalines/jerboa#496] opened 2023-06-10 10:40 UTC
** Jerboa Version **
0.0.32

**Describe the bug**

When I glance over the apps side menu in light theme mode I can barely read my accounts name due to the text color being close to the color of the background (gray), and since the text color the account name seems to be constant across all themes, the account name is conversely very readable in the Dark and Black themes. 

This might not be that huge of an issue at the time, but when you might have multiple accounts that you switch between them it can be a little harder to tell at first glance which account you're on. 

**To Reproduce**

Change the app's theme to light theme and go to the side menu.

**Comment by MV-GH** [comment] 2023-06-10 11:48
Duplicate of #476

**Comment by tarekzoabi19** [comment] 2023-06-10 12:40
> Duplicate of #476 

I'll have it closed.

**Closed** 2023-06-10 12:40 UTC
Labels: bug
