### ISSUE TITLE
Clicking post, voting it and going back will not display your vote

### ISSUE THREAD

**Issue by Fxsch** [dessalines/jerboa#1273] opened 2023-11-10 09:17 UTC
### Jerboa Version

0.0.50

### Android Version + Phone

Android 13, Nothing Phone 1

### Describe The Bug

If you click on a post and up- or downvote it, your vote will not be displayed when you go back to the home feed. Clicking the post again and going back fixes it most of the time, sometimes you need to do that multiple times. The app probably just needs to reload your vote from the server for the post you just clicked on after you go back to the home feed.

### To Reproduce

1. Click on a post
2. Up- or downvote it
3. Go back to the home feed
4. No vote by you on that post

**Comment by dessalines** [comment] 2024-02-15 19:25
Dupe of #912

**Closed by dessalines** 2024-02-15 19:25 UTC
Labels: bug
