### ISSUE TITLE
Link Preview 

### ISSUE THREAD

**Issue by RootVerde** [dessalines/jerboa#434] opened 2023-06-06 04:34 UTC
At the moment clicking a link will immediately launch to the URL. A link Preview on hypertext or just a confirmation before navigating would be beneficial. A miss touch of the screen can send you to a website without any warning and if it was hypertext, without you knowing where it's taking you.

**Comment by dessalines** [comment] 2023-06-06 19:25
Somewhat duplicate of #396

**Comment by twizmwazin** [comment] 2023-06-06 19:58
I see these two issues as separate. A fix to this issue would be a discord-style popup "This link goes to an external site, are you sure you want to open it?" along with a full preview of that link. #396 is just allow those links to then be opened in a custom tab rather than in the user's browser.

**Comment by TrollBlox** [comment] 2023-06-07 17:25
I like the way Boost does it where you can hold down on a link to get options and see where it actually goes.

**Comment by mpusch88** [comment] 2023-06-18 18:20
Rif implementation is also great

![Screenshot_20230618-112018.png](https://github.com/dessalines/jerboa/assets/11446016/7b46e819-9cb8-4be1-b476-3390eedecb01)

**Comment by RootVerde** [comment] 2023-08-31 18:30
Thank you for the feature and current state of things. For me the primary reason for a preview on all clicks is to prevent malicious links. I will accidentally click a link and at the moment don't know if I am heading to an article about the post or if my YouTube app is going to be launched. For me that is not a good thing but I recognize form versus function as not everyone wants a popup for every link they interact with. For that reason I say take a consensus on if having the option to de-obfuscate links via long press is sufficient as I don't think I can speak for the majority.

**Comment by MV-GH** [comment] 2023-08-31 18:55
Would a option for warning about opening external links completely fulfill this request? (If so I am going to reword this feature request). Also would you prefer a reduced link preview form only containing the open link section or the full sections including share/save?

**Comment by dessalines** [comment] 2023-08-31 20:33
I agree with @RootVerde , the long-press functionality you've added fixes this one, and lets you see if that link is external or not. 

Other suggestions can be in new issues.

**Closed by dessalines** 2023-08-31 20:33 UTC
Labels: enhancement, 3 - medium priority
