### ISSUE TITLE
Internal image and video viewer

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#433] opened 2023-06-06 00:10 UTC
I'd like to expand on issue #397 but specifically on the main page. Instead of opening videos and images in browser and apps, there should be an internal viewer. For images, it should support galleries with thumbnail viewer (film strip style possibly?), downloads, text, zoom, copying/sharing links, and for videos/gifs it should have a speed control. And also the ability to swipe away the viewer.

**Comment by dessalines** [comment] 2023-06-06 19:14
Dupe of #397

**Closed by dessalines** 2023-06-06 19:14 UTC
