### ISSUE TITLE
Comment reply/message UI in 'Inbox' tab gone after 0.0.33

### ISSUE THREAD

**Issue by chbsk** [dessalines/jerboa#550] opened 2023-06-12 01:03 UTC
** Jerboa Version **
Type the version from the settings here.
0.0.33
Phone: H8276 Sony Xperia XZ2
Android: 9
Build: 52.0.A.11.32

**Describe the bug**

UI options to mark as read/goto comments etc are all gone after 0.0.33

**To Reproduce**

1. Go to 'Messages'
2. Click on any unread message
3. No options available. Comment still collapsible but not UI buttons. See image

![Screenshot_20230611-195834](https://github.com/dessalines/jerboa/assets/14252817/3297edee-3087-469b-a538-96c5ac7891ed)

**Comment by zestygrass** [comment] 2023-06-12 04:04
I can also reproduce this behaviour.
I did not use the previous versions, so I don't know if this is intentional behaviour.

A side note, should comment replies be clickable in inbox? as in, go the post and scroll down to that comment?

**Comment by twizmwazin** [comment] 2023-06-14 03:08
Duplicate of #525

**Closed by twizmwazin** 2023-06-14 03:08 UTC
Labels: bug, 5 - high priority
