### ISSUE TITLE
Make it easier to open a post in list view

### ISSUE THREAD

**Issue by Chris-Kropp** [dessalines/jerboa#784] opened 2023-06-21 01:48 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Currently in list view the community and user links take up the middle 1/3 of the clickable area to open a post with a short title
![image](https://github.com/dessalines/jerboa/assets/52611624/9c10eb22-7ba0-4771-b783-ee7ae2985152)

By moving the comment count to the middle of the post, the 2/3 that open the post are next to each other, making it harder to accidentally open the community or user page.
![image](https://github.com/dessalines/jerboa/assets/52611624/9ef43019-9190-4e15-b862-1eac98fd24a4)

**Comment by twizmwazin** [comment] 2023-06-21 05:51
Duplicate of #488

**Closed by twizmwazin** 2023-06-21 05:51 UTC
Labels: enhancement
