### ISSUE TITLE
admin tools: allow to add admins

### ISSUE THREAD

**Issue by firefoxlover** [dessalines/jerboa#1430] opened 2024-03-06 16:45 UTC
In Lemmy WebUI admins can add other users as admins when they comment or post in that community under administration of the user.

This is not possible in Jerboa, a missing feature of the admin tools.

I would prefer a more intuitive feature like adding users from their user info page, or from the community info page, but thats not critical.

Using latest Github release.

**Comment by MV-GH** [comment] 2024-03-06 17:55
duplicate of #1407

**Closed by MV-GH** 2024-03-06 17:55 UTC
