### ISSUE TITLE
Saved icon in bottom bar says "Search"

### ISSUE THREAD

**Issue by PeakMars** [dessalines/jerboa#741] opened 2023-06-18 13:11 UTC
** Jerboa Version **
0.0.34

**Describe the bug**
See picture below and title
![IMG_20230618_090618](https://github.com/dessalines/jerboa/assets/78813373/ddf529a6-4617-4001-be5c-0df8723acb28)

**To Reproduce**
Open jerboa app

The only thing I've done since installing the app is logging in, so I'm guessing there's no steps to reproduce the bug other than opening the app.

Sorry if this isn't a great report, this is my first bug report :)

**Comment by daviessm** [comment] 2023-06-18 13:17
Duplicate of #604, already fixed.

**Closed** 2023-06-19 19:47 UTC
Labels: bug
