### ISSUE TITLE
Please remove automatic language setting. 

### ISSUE THREAD

**Issue by seelebrn** [dessalines/jerboa#846] opened 2023-06-23 11:00 UTC
As title. Alternative option would be to let people chose their own language.
It's very annoying when you're forced into using a bad localization, which is also totally messing up the UI. 

Edit : Maybe it's already possible to so it as a logged user but I wouldn't know. I can't log in to my instance due to different server versions \o/

Thanks for all your work, I hope you'll take this inti consideration.

**Comment by MV-GH** [comment] 2023-06-23 14:42
Duplicate of #755

**Comment by MV-GH** [comment] 2023-07-11 20:11
You can now choose the language from the app settings #873

**Closed by MV-GH** 2023-07-11 20:11 UTC
Labels: enhancement
