### ISSUE TITLE
Notification for new posts from selected communities

### ISSUE THREAD

**Issue by VicMCA** [dessalines/jerboa#1054] opened 2023-07-18 02:35 UTC
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Would it be feasible to add communities to a "watch for new posts" list of sorts, so that we could receive notifications on Android/iOS for them? e.g.: I subscribed to the !news@lemmyrs.org and would like to be notified about new posts there.

Probably it'd be good to limit how often Jerboa could check for updates, with a minimum of 1h perhaps.

**Comment by Heus-Sueh** [comment] 2023-12-20 01:30
🚀

**Comment by dessalines** [comment] 2023-12-20 13:30
Besides RSS, a bigger task for next year is to rework notifications for lemmy: https://github.com/LemmyNet/lemmy/issues/2631

**Comment by dessalines** [comment] 2024-02-10 23:24
Dupe of #275

**Closed by dessalines** 2024-02-10 23:24 UTC
Labels: enhancement
