### ISSUE TITLE
Do a version check on login, to say whether the current version of jerboa supports your server.

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#701] opened 2023-06-16 13:53 UTC
IE have a popup error that says ("Version of lemmy unsupported by X instance. Ask your server administrators to upgrade lemmy.")

This is necessary, since logging into pre `0.18` versions will fail, due to breaking API changes.

**Comment by beatgammit** [comment] 2023-06-16 14:24
Is there a mechanism for admins to be notified of an API breakage? What about instances to auto-block other instances when API versions are incompatible?

**Comment by sockenklaus** [comment] 2023-06-17 02:01
Isn't this a duplicate of #673?

**Comment by twizmwazin** [comment] 2023-06-19 07:02
Duplicate of #673

**Closed by twizmwazin** 2023-06-19 07:02 UTC
Labels: enhancement
