### ISSUE TITLE
Can't turn on notifications on my phone

### ISSUE THREAD

**Issue by Mizu-6079** [dessalines/jerboa#622] opened 2023-06-14 01:05 UTC
** Jerboa Version **
v0.0.34-alpha

**Describe the bug**
When I go to app settings on my phone,  Allow Notifications is toggled off and darkened; can't be toggled on. 

**To Reproduce**

1. Press and hold app icon on home screen
2. Click on App info
3. Click on manage notification
4. See that it's toggled off

**Comment by twizmwazin** [comment] 2023-06-14 01:38
Duplicate of #275

**Closed by twizmwazin** 2023-06-14 01:38 UTC
Labels: bug
