### ISSUE TITLE
Support for UnifiedPush

### ISSUE THREAD

**Issue by Generator** [dessalines/jerboa#644] opened 2023-06-14 13:58 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **
Support for (inbox) push notifications via UnifiedPush.

**Comment by shortwavesurfer2009** [comment] 2023-06-14 14:07
Yes, i would love to see this. However, i think the lemmy server code needs to support sending to a push server too so i am unsure about this one until lemmy itself adds it (which they may support already, idk)

**Comment by twizmwazin** [comment] 2023-06-14 18:17
Duplicate of #275

**Closed by twizmwazin** 2023-06-14 18:17 UTC
Labels: enhancement

**Comment by Daxiongmao87** [comment] 2023-06-15 17:37
> Yes, i would love to see this. However, i think the lemmy server code needs to support sending to a push server too so i am unsure about this one until lemmy itself adds it (which they may support already, idk)

I suppose polling would work but it would be delayed and probably inefficient.

**Comment by shortwavesurfer2009** [comment] 2023-06-15 19:09
> > Yes, i would love to see this. However, i think the lemmy server code needs to support sending to a push server too so i am unsure about this one until lemmy itself adds it (which they may support already, idk)
> 
> I suppose polling would work but it would be delayed and probably inefficient.

Only as delayed as your poll interval, but yes, bad idea. Another task to wake up and use network and battery plus then the server has to respond to a majority of the requests with "nothing new so stop bugging me"
