### ISSUE TITLE
Stutter/skipping above 60hz

### ISSUE THREAD

**Issue by powermaker450** [dessalines/jerboa#929] opened 2023-06-30 13:40 UTC
**Jerboa Version**
0.0.37

**Android version + phone**
A13, Galaxy S20 5G (USA)

**Describe the bug**
Scrolling on Jeroba while tbe screen is set to anything above 60hz results in noticeable stuttering.

**To Reproduce**

1. Set the screen refresh rate to anything above 60hz
2. Open the app and scroll on the homepage.

Only on the homepage is there this strange hitching while scrolling. In the settings page for example, I can scroll normally with no visual issues. It isn't an issue with loading new content either, as I can scroll up and down on the same content on the homepage and the stuttering will still be present. When switching to 60hz there is no skipping/stutter and everything works as expected.

**Comment by twizmwazin** [comment] 2023-07-02 05:09
Duplicate of #445

**Closed by twizmwazin** 2023-07-02 05:09 UTC
