### ISSUE TITLE
View comment thread while replying 

### ISSUE THREAD

**Issue by 782125** [dessalines/jerboa#632] opened 2023-06-14 08:03 UTC
- [ x] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

On Boost for Reddit when replying to comments, you could click a link called context that would show the current comment thread while you are replying, very handy to keep track and quote from. Currently it only shows the one reply and the only way to view the thread is to go back into the post and scroll to find the comment thread you are replying to.

**Comment by dessalines** [comment] 2024-02-14 19:24
Dupe of #480

**Closed by dessalines** 2024-02-14 19:24 UTC
Labels: enhancement, 3 - medium priority
