### ISSUE TITLE
Collapsing cross posts into the same post in the post feed

### ISSUE THREAD

**Issue by Ategon** [dessalines/jerboa#1274] opened 2023-11-14 00:03 UTC
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

Behaviour in lemmy-ui is to collapse posts with the same url into the same post in the post feed (showing the duplicates in a cross-posted to section). Jerboa doesn't follow that standard and instead shows all of the posts separatedly which can flood the feed if the same thing is being crossposted to multiple spots

![6cfb2660-e5d5-47db-a789-21201bc0e166](https://github.com/dessalines/jerboa/assets/73616169/96ec1c43-1a9e-4a0d-af7b-0636c7585c98)

![c1fa49a0-ce39-409c-8d30-dd3ffb0eed5d](https://github.com/dessalines/jerboa/assets/73616169/1db4dc9b-e6ef-42f0-b302-a85b782a3ae0)

This feature is very useful for posts to be able to be posted freely to multiple places at once, especially in instances that encourage cross-posting due to communities frequently having topic overlap

**Comment by dessalines** [comment] 2024-02-11 05:15
Dupe of #13

**Closed by dessalines** 2024-02-11 05:15 UTC
Labels: enhancement
