### ISSUE TITLE
ability to search through your own comments and posts

### ISSUE THREAD

**Issue by RustoMCSpit** [dessalines/jerboa#1125] opened 2023-08-02 19:15 UTC
### Pre-Flight checklist

- [X] Did you check to see if this issue already exists?
- [X] This is a single feature request. (Do not put multiple feature requests in one issue)
- [X] This is not a question or discussion. (Use https://lemmy.ml/c/jerboa for that)

### Describe The Feature Request Below

in your profike

**Comment by dessalines** [comment] 2024-02-10 23:30
Dupe of #27 . Lemmy's back end does allow you to filter by user.

**Closed by dessalines** 2024-02-10 23:30 UTC
Labels: enhancement
