### ISSUE TITLE
Missing time units (d/h/m) when Russian language is primary 

### ISSUE THREAD

**Issue by Snow4DV** [dessalines/jerboa#766] opened 2023-06-19 22:33 UTC
**Jerboa Version**
0.0.33 latest Google play version 

**Describe the bug**
Missing units when Russian locale is set on the phone: no d/m/h etc

**To Reproduce**

1. Set Russian language as primary one in settings
2. Open feed
![Screenshot_2023-06-20-01-32-10-63_a10f969cf1c4adf2c503042b459b8476](https://github.com/dessalines/jerboa/assets/32912696/03b1302b-2528-49b6-866d-24f9edf6d65a)
![Screenshot_2023-06-20-01-29-41-70_a10f969cf1c4adf2c503042b459b8476](https://github.com/dessalines/jerboa/assets/32912696/72ed66b5-6719-47e3-9cdd-d733bdeab766)

**Comment by twizmwazin** [comment] 2023-06-19 22:38
Duplicate of #539

**Closed by twizmwazin** 2023-06-19 22:38 UTC
Labels: bug
