### ISSUE TITLE
Weird error null thing whenever I check certain sidebar stuff

### ISSUE THREAD

**Issue by ColdyCold** [dessalines/jerboa#370] opened 2023-06-02 12:15 UTC
![Screenshot_20230602-042659_Jerboa for Lemmy](https://github.com/dessalines/jerboa/assets/135335385/e2d095e2-dc26-4d8e-97e6-da037510e7a7)

For whatever reason when I clicked on a community in a sidebar, this dummy thing popped up, I tried to recreate it but wasn't able to through what I did before.

https://github.com/dessalines/jerboa/assets/135335385/c524f9ad-1174-4189-9845-6c19efe578af

Though this happened when I tried to recreate the steps of trying to hit the sidebar stuff again where it brought up this glitched home menu in the wrong category.

**Comment by dessalines** [comment] 2023-06-02 14:55
This happens when you click on a community, inside the another community's sidebar? 

Deep linking is currently pretty bugged.

**Comment by ColdyCold** [comment] 2023-06-02 15:55
> This happens when you click on a community, inside the another community's sidebar?
> 
> Deep linking is currently pretty bugged.

Yeah it happens whenever I click on one as you're describing.

**Comment by dessalines** [comment] 2023-06-04 11:50
dupe of #395

**Closed by dessalines** 2023-06-04 11:50 UTC
