### ISSUE TITLE
No login button / option

### ISSUE THREAD

**Issue by Alatarius** [dessalines/jerboa#722] opened 2023-06-17 14:07 UTC
** Jerboa Version **
Whatever is in the google play store. Couldn't access settings without logging in first. (See title)

**Describe the bug**
There is no login button or option in settings to let me login to my lemmy account. Unable to view or post without logging in first

**To Reproduce**
Download app and open

[edited for spelling error]

**Comment by MV-GH** [comment] 2023-06-17 16:26
At least post pictures because I cant reproduce this

**Comment by Alatarius** [comment] 2023-06-17 16:49
I see from your image above that the login is hidden. This should be more visible for new users such as myself. The down arrow on anonymous is hard for me to see since I am visually impaired

**Comment by MV-GH** [comment] 2023-06-17 16:53
Do you have suggestions that could improve the UX? we have had some people report before that they couldnt find it.
At most I think of rn is on first startup It shows a popup to directly bring you to the login page.

**Comment by MV-GH** [comment] 2023-06-17 17:02
See https://github.com/dessalines/jerboa/issues/719

**Comment by Alatarius** [comment] 2023-06-17 17:15
> 
One suggestion is to make "Add account" more visible instead of making it a sub category of anonymous. Also it would be helpful to make a dedicated button either in the hamburger menu button or have it as a startup function when you open the app for the first time. If they decline at start up, give people instructions on how to add their account(s) later.

I would like to thank you for your quick response and being open to suggestions. This goes a long way in building user trust. Keep up the great work.

**Comment by twizmwazin** [comment] 2023-06-19 20:01
Closing as a duplicate of #719

**Closed by twizmwazin** 2023-06-19 20:01 UTC
Labels: bug
