### ISSUE TITLE
Rotating the screen resets me to Local view

### ISSUE THREAD

**Issue by Fabricio872** [dessalines/jerboa#769] opened 2023-06-20 06:00 UTC
**Jerboa Version**
0.0.34

**Describe the bug**

**To Reproduce**

1. Go to "All" view
2. Rotate the phone to landscape mode
3. Now you shold be in "Local" view and you have to switch to "All" or "Subscribed" view and scroll all the way to post you were reading

**In the case of a crash**

Please include the logs.
See [this post](https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log) to get the logs.
`adb logcat com.jerboa` Should give you the relevant logs.

**Comment by nahwneeth** [comment] 2023-06-20 06:25
Duplicate of #559.  Since a fix has been merged, do consider closing the issue.

**Comment by Fabricio872** [comment] 2023-06-20 06:36
Sorry i didnt found that one thank you i am closing it.

**Closed** 2023-06-20 06:36 UTC
