### ISSUE TITLE
Crash when opening a specific post

### ISSUE THREAD

**Issue by aqeeliz** [dessalines/jerboa#380] opened 2023-06-03 06:10 UTC
Opening https://beehaw.org/post/417477 (which shows up in my subscribed list) crashes the app. I can open other posts from same community without any issue.

I am using 0.0.30 on Galaxy Tab A7 running Android 12.

Let me know if you need anymore info.

**Comment by twizmwazin** [comment] 2023-06-03 23:05
I could not reproduce this on my Pixel 5 with Android 13.

**Comment by AdamDoesThingsSometimes** [comment] 2023-06-05 00:01
I have the same issue with this link: https://lemmy.one/post/7580

As soon as it goes to load the comments, the app immediately crashes.

I'm on a Samsung S10, Android 12 using Jerboa 0.030 :)

**Comment by dessalines** [comment] 2023-06-05 12:08
This was fixed in 0.0.31

**Closed by dessalines** 2023-06-05 12:08 UTC
