### ISSUE TITLE
Search button isn't actually search

### ISSUE THREAD

**Issue by jordan1776** [dessalines/jerboa#648] opened 2023-06-14 14:46 UTC
** Jerboa Version **
0.0.34

**Describe the bug**
The "search" is actually a "communities" button. I know that the icon was changed on the navigation bar. The "search" is expected to go to page for searching for comments, posts, and users with sorting (new, top) and filtering by time ([this page](https://beehaw.org/search)). I don't believe Jerboa has this feature yet so this might be an enhancement, but it is a bug that the button doesn't do what is labeled (to a layman).

I see  #27 and #467, this is mostly about the button itself, less of the feature.

**Comment by beatgammit** [comment] 2023-06-14 14:58
Perhaps as a stopgap, we could include toggles or tabs to search other content, but make them not interactible until the feature is implemented. That way it's self documenting as to what's supported and what's not.

**Comment by painkiller1717** [comment] 2023-06-21 13:48
> Perhaps as a stopgap, we could include toggles or tabs to search other content, but make them not interactible until the feature is implemented. That way it's self documenting as to what's supported and what's not.

Would be great add a button to search not only the lists of communities, also in comments, posts, and the term in whole Lemmy server, for example on [Lemmy.world]().

I went to search _mirtazapine_ because I'm doing a gradual tapper since yesterday at night, and just discovered that the search button is only to search communities. That should be fixed and a future function implemented, because is really useful and wihout it there are limitations in search of informational about some thing concrete.

**Comment by dessalines** [comment] 2024-02-10 22:04
Dupe of #27

**Closed by dessalines** 2024-02-10 22:04 UTC
Labels: bug, 4 - medium/high priority
