### ISSUE TITLE
Default Listing and Sort types not respected

### ISSUE THREAD

**Issue by zacharee** [dessalines/jerboa#857] opened 2023-06-23 20:48 UTC
**Jerboa Version**
0.0.35

**Describe the bug**
I have the default Listing and Sort types set to Subscribed and TopDay respectively. When I open the app, I'm put on Local and Active.

My instance is sh.itjust.works, and I've tried resetting the app data and changing the settings to other values and back.

The settings are remembered correctly in the settings screen, but seem to be ignored.

**To Reproduce**

1. Go to Settings >> <user> settings
2. Set "Default Listing Type" to Subscribed and "Default Sort Type" to TopDay.
3. Scroll down to the bottom and press "Save".
4. Close and reopen the app and it will go back to Local and Active.

**Comment by nahwneeth** [comment] 2023-06-24 01:16
Fixed by #854

**Comment by kensand** [comment] 2023-06-25 01:46
#854 has introduced a new bug for me - attempting to change the sort behavior or listing type on the HomeActivity loads the correct sort behavior/listing type for a moment and then reloads the home back to All/Active.

Reverting 058e3c3e fixes the issue for me, so I'm almost positive that is the cause.

**Comment by kensand** [comment] 2023-06-25 01:52
Yup, I'm pretty sure the issue is that [this line](https://github.com/dessalines/jerboa/blob/243bc22b2faeda9364e9f5e9fb57a912e6564957/app/src/main/java/com/jerboa/Utils.kt#L723) is called before loading the posts now, which just overwrites the potentially user-selected Sort/Type. How that gets remedied, I don't have an answer yet

**Comment by nahwneeth** [comment] 2023-06-26 04:22
@kensand

I wasn't able to reproduce this. The line you've linked only runs during startup, account switch & sign out. I did find some potential rewrite of the defaults (& the other way - the defaults overwriting home filters). I have tried to addressed it in #817. Could you please confirm if that fixes your issues? If not, would appreciate if you provided more info on what actions were made after changing the settings.

**Comment by kensand** [comment] 2023-06-27 02:11
@nahwneeth I am verified - I pulled the latest commits and it seems to be working now - not sure what was happening, whether it be a glitch in the server's settings being saved or in Jerboa itself :shrug:

**Comment by nahwneeth** [comment] 2023-06-27 02:17
Hey, yeah I updated it to read from the local db. The changes you made will not sync with the server and will not carry over if you use a new device.

**Comment by MV-GH** [comment] 2023-07-25 22:04
Should be fixed now

**Closed by MV-GH** 2023-07-25 22:04 UTC
Labels: bug
