### ISSUE TITLE
Long-press hyperlink text to reveal destination URI

### ISSUE THREAD

**Issue by jago-w1k** [dessalines/jerboa#709] opened 2023-06-16 23:23 UTC
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

I'm copying the text of a [post I made in the jerboa community at lemmy.ml](https://lemmy.ml/post/1285175); it was suggested I post here for a better chance at traction:

> On mobile I use(d) Relay for reddit browsing. The app has a feature that I miss in Jerboa.
> 
> In posts/comments, hyperlinked text can be long-pressed to reveal the destination in a pop-up overlayed on the link (sorry, I don’t know the proper term for this UI tool) without actually opening to the link. Upon tapping off the pop-up, it closes and I tap on the URI to follow through to it, or not, as I wish. In Jerboa, pressing a hyperlink only opens it, site unseen (pun intended).
> 
> This change would be useful because sometimes I don’t want to open the linked page, given the target (e.g. youtube, instagram).
> 
> In Jerboa I see no way of discovering the URI of a hyperlink without following to it, which would be convenient to avoid.

In the comments of this post, user [@NoTime@lemmy.one](https://lemmy.ml/u/NoTime@lemmy.one) replied with a screenshot of exactly what I am describing. I'm [including that image here via off-site image host](https://i.postimg.cc/ryRDbQhQ/Relay-Screenshot.gif). I hope that's okay.

**Comment by anna-s-h** [comment] 2023-06-19 10:13
If possible, an additional option to attempt to open the link in jerboa regardless of android settings would be very helpful.

**Comment by twizmwazin** [comment] 2023-06-19 22:46
Duplicate of #434

**Closed by twizmwazin** 2023-06-19 22:46 UTC
Labels: enhancement
