### ISSUE TITLE
"Settings" menu and submenus cannot scroll

### ISSUE THREAD

**Issue by ESodikromo** [dessalines/jerboa#654] opened 2023-06-14 19:54 UTC
** Jerboa Version **
Type the version from the settings here: 0.0.33

**Describe the bug**
Downloaded Jerboa, attempted to edit the settings. I cannot scroll down to access settings lower than the screen. This is extra apparent in landscape mode. Scrolling works in other menus like home and search.

**To Reproduce**

1. On a Samsung SM-G781U1 (S20FE) on Android 13, One UI 5.1
2. From Home, click on the hamburger icon and then to settings
3. Select either "Look and feel" or "About"
4. Confirm unable to scroll in both portrait and landscape mode.

**Comment by thebino** [comment] 2023-06-14 20:25
I cannot reproduce it.

https://github.com/dessalines/jerboa/assets/841681/59e56fbc-6023-45e0-8b2e-9083669fb354

**Comment by burtek** [comment] 2023-06-14 21:00
I have the same issue. S20 FE, let me know if you need any logs/data to debug

**Comment by twizmwazin** [comment] 2023-06-14 21:44
The look and feel page is fixed in n 0.0.34 and the about page is fixed on master and will be in 0.0.35

**Closed by twizmwazin** 2023-06-14 21:44 UTC
Labels: bug
