### ISSUE TITLE
Intuitive login or register

### ISSUE THREAD

**Issue by soldacad** [dessalines/jerboa#624] opened 2023-06-14 05:31 UTC
- [X ] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

On pressing the profile favicon a message appears to "login first". This was my intuitive attempt to find the login, so looking elsewhere was a mystery-tour (without a guide). Could this favicon instead direct users to the login, if we're otherwise not logged in? The error message seems to come too early considering there is little or no splash or guided message.

**Comment by twizmwazin** [comment] 2023-06-14 07:14
Duplicate of #346

**Comment by MV-GH** [comment] 2023-06-14 07:15
Kinda duplicate of  [#346](https://github.com/dessalines/jerboa/issues/346), the problems is that you have to find a balance in between finding login easily and not constantly redirect users to login who anonymously and accidentally click on of those buttons.
Maybe a suggestion on the first time of the app start to login that actually redirects and keep the others as toasts? That way new users get prompted to login and existing anon users don't get redirected.

**Closed by twizmwazin** 2023-06-14 07:14 UTC
Labels: enhancement

**Comment by twizmwazin** [comment] 2023-06-14 07:25
There is an open issue to make the various small touch targets disabl-able in the home/community views, and the nav bar ready supports being disabled. Comment action bars can be hidden by default. I think if a user wants to browse anonymously those settings should allow them to hide the majority of the buttons that would otherwise redirect them.
